-- create "table_one" table
CREATE TABLE "table_one" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "something" character varying NOT NULL,
    PRIMARY KEY ("id")
);
-- create index "table_one_something_key" to table: "table_one"
CREATE UNIQUE INDEX "table_one_something_key" ON "table_one" ("something");
